services:

    user_ban_operator:
        class: AppBundle\Service\UserBanOperator
        arguments:
            - @user_manager
            - @automatic_ban_criteria

    user_listener:
        class: AppBundle\EventListener\UserListener
        arguments:
            - @user_repository
            - @user_ban_operator
        tags:
            - { name: kernel.event_listener, event: comment.deleted, method: onCommentDeleted }

    distinct_deleter_criteria:
        class: AppBundle\Criteria\DistinctDeleterCriteria
        arguments:
            - 2
            - @comment_repository

    deleted_comment_criteria:
        class: AppBundle\Criteria\DeletedCommentsCriteria
        arguments:
            - 3
            - @comment_repository

    automatic_ban_criteria:
        class: AppBundle\Criteria\AndCriteria
        arguments:
            - [@deleted_comment_criteria, @distinct_deleter_criteria]

    comment_manager:
        class: AppBundle\Service\CommentManager
        arguments:
            - @event_dispatcher

    user_manager:
        class: AppBundle\Service\UserManager
        arguments:
            - @event_dispatcher

    comment_repository:
        class:     Doctrine\ORM\EntityRepository
        factory:   [@doctrine.orm.entity_manager, getRepository]
        arguments: [AppBundle\Entity\Comment]

    user_repository:
        class:     Doctrine\ORM\EntityRepository
        factory:   [@doctrine.orm.entity_manager, getRepository]
        arguments: [AppBundle\Entity\User]

    post_repository:
        class:     Doctrine\ORM\EntityRepository
        factory:   [@doctrine.orm.entity_manager, getRepository]
        arguments: [AppBundle\Entity\Post]

    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: AppBundle\Utils\Slugger

    markdown:
        class: AppBundle\Utils\Markdown

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: [@markdown, %app_locales%]
        tags:
            - { name: twig.extension }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.redirect_to_preferred_locale_listener:
        class: AppBundle\EventListener\RedirectToPreferredLocaleListener
        arguments: [@router, %app_locales%, %locale%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
